
import { useMutation, useQueryClient } from "@tanstack/react-query";
import type { RackCreate, RackUpdate } from "@/types/Rack";
import { MockDB } from "@/mocks/rackData";

interface UseRackMutationsOptions {
    token?: string | null;
}

export const useRackMutations = ({ token }: UseRackMutationsOptions) => {
    const queryClient = useQueryClient();

    const createRack = useMutation({
        mutationFn: async (data: RackCreate) => {
             // Mock Create
             // We need to cast data to IRack-like object mostly, but ID is generated by MockDB
             // RackCreate should match Omit<IRack, "id"> essentially
             return MockDB.add(data as any);
        },
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ["racks"] });
            // Alert removed as requested
        },
    });

    const updateRack = useMutation({
        mutationFn: async (data: RackUpdate) => {
            // Mock Update
            return MockDB.update(data as any);
        },
        onSuccess: () => {
             queryClient.invalidateQueries({ queryKey: ["racks"] });
        },
    });

    const deleteRack = useMutation({
        mutationFn: async (id: number) => {
            // Mock Delete
            return MockDB.delete(id);
        },
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ["racks"] });
        },
    });

    return {
        createRack,
        updateRack,
        deleteRack,
    };
};
