import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useVerify2FA } from "@/hooks/use2FA";
import { Label } from "@radix-ui/react-label";
import { useQueryClient } from "@tanstack/react-query";
import { useState, type FC } from "react"

interface Setup2FaModalProps {
    token: string;
    qrCodeImage: string;
    setIs2FAModalOpen: (open: boolean) => void;
}

const Setup2FaModal: FC<Setup2FaModalProps> = ({ token, qrCodeImage, setIs2FAModalOpen }) => {
    const queryClient = useQueryClient();
    const [step, setStep] = useState<1 | 2>(1)
    const [verificationCode, setVerificationCode] = useState("")
    const verify2FAMutation = useVerify2FA(token || "")
    const handleVerifyCode = () => {
        verify2FAMutation.mutate(verificationCode, {
            onSuccess: (data) => {
                console.log("Verification successful", data)
                setIs2FAModalOpen(false)
                queryClient.invalidateQueries({ queryKey: ["user"] })
                // Optionally refresh user profile or show success message
            },
            onError: (error) => {
                console.error("Verification failed", error)
            }
        })
    }

    return (
        <div className="fixed inset-0 z-50 bg-black/80 backdrop-blur-sm data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 flex items-center justify-center p-4">
            <div className="bg-background border rounded-lg shadow-lg w-full max-w-md p-6 relative animate-in fade-in-0 zoom-in-95 duration-200">
                <div className="flex flex-col space-y-1.5 text-center sm:text-left mb-4">
                    <h3 className="text-lg font-semibold leading-none tracking-tight">
                        {step === 1 ? "Enable 2FA" : "Verify 2FA"}
                    </h3>
                    <p className="text-sm text-muted-foreground">
                        {step === 1 
                            ? "Scan the QR code below with your authenticator app to enable 2-Factor Authentication." 
                            : "Enter the code generated by your authenticator app."}
                    </p>
                </div>
                <div className="flex justify-center py-4 flex-col items-center gap-4">
                {step === 1 ? (
                    qrCodeImage ? (
                        <img src={qrCodeImage} alt="2FA QR Code" className="w-48 h-48 border rounded-md" />
                    ) : (
                        <p>Loading QR Code...</p>
                    )
                ) : (
                    <div className="w-full max-w-xs">
                        <Label htmlFor="verification-code" className="sr-only">Verification Code</Label>
                        <Input 
                            id="verification-code" 
                            placeholder="Enter 6-digit code" 
                            value={verificationCode}
                            onChange={(e) => setVerificationCode(e.target.value)}
                            className="text-center text-lg tracking-widest"
                        />
                    </div>
                )}
                </div>
                <div className="flex flex-col-reverse sm:flex-row sm:justify-end sm:space-x-2 mt-4">
                <Button
                    type="button"
                    variant="outline"
                    onClick={() => setIs2FAModalOpen(false)}
                    className="mt-2 sm:mt-0"
                >
                    Cancel
                </Button>
                {step === 1 ? (
                    <Button type="button" onClick={() => setStep(2)}>
                        Next
                    </Button>
                ) : (
                    <Button type="button" onClick={handleVerifyCode} disabled={!verificationCode}>
                        Done
                    </Button>
                )}
                </div>
            </div>
        </div>
    )
}
export default Setup2FaModal;